kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: my-python
          image: python-image:latest
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: OPENSHIFT_API_URL
              value: "https://kubernetes.default.svc"
            - name: NAMESPACE
              value: "virt-provision" 
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: provisioning-sa-token-job-creator-sa-dockercfg-j7ng2
                  key: token
            - name: PORT
              value: "8080"
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"
---
kind: Service
apiVersion: v1
metadata:
  name: my-python
spec:
  ports:
    - name: http-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: python-app
